KPV1/blog/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auths.login');
});



Route::get('/login','AdminController@login')->name('login');
Route::post('/postlogin','AdminController@postlogin');
Route::get('/logout','AdminController@logout');


Route::group(['middleware'=>['auth','checkRole:Kasir,Pimpinan,Pengawas,Mantri']],function (){

//    Route::get('/petugas','PetugasController@viewpetugas');
//    Route::post('/petugas/create','PetugasController@create');
//    Route::get('/petugas/{id}/delete','PetugasController@delete');
//    Route::post('/petugas/{id}/update','PetugasController@update');

    Route::get('/formpegawai', 'Home@formpetugas');
    Route::post('/simpanpegawai', 'Home@simpanpegawai');
    Route::get('/getpegawai/{id}', 'Home@getpegawai');
    Route::post('/updatepegawai', 'Home@updatepegawai');
    Route::get('/delete/{id}', 'Home@hapuspegawai');
    Route::get('/datapetugas','Home@ajax_list');
    Route::post('/petugas/create','Home@simpanpegawai');

    Route::resource('nasabah','NasabahController');
    Route::get('/nasabah','NasabahController@viewnasabah');
    Route::get('/nasabah/{id}/delete','NasabahController@delete');

    Route::get('/formmodal', 'Home@formmodal');
    Route::get('/datamodal', 'Home@list_modal');
    Route::post('/simpanmodal', 'Home@simpanmodal');
    Route::get('/getmodal/{id}', 'Home@getmodal');
    Route::post('/updatemodal', 'Home@updatemodal');

    Route::get('/formangsuran', 'AngsuranController@formangsur');
    Route::get('/dataangsuran', 'AngsuranController@list_angsuran');
    Route::post('/simpanangsuran', 'AngsuranController@simpanangsuran');
    Route::get('/getid/{id}', 'AngsuranController@getID');
    Route::get('/getangsuran/{id}', 'AngsuranController@getangsuran');
    Route::get('/selectangsuran/{id}', 'AngsuranController@selectangsuran');
    Route::post('/updateangsuran', 'AngsuranController@updateangsuran');

    Route::get('/formpinjaman', 'PinjamanController@formpinjaman');
    Route::get('/datapinjaman', 'PinjamanController@list_pinjaman');
    Route::post('/simpanpinjaman', 'PinjamanController@simpanpinjaman');
    Route::get('/getpinjaman/{id}', 'PinjamanController@getpinjaman');
    Route::post('/updatepinjaman', 'PinjamanController@updatepinjaman');



    Route::post('/admin','AdminController@admin');

});

Route::group(['middleware'=>['auth','checkRole:Kasir,Mantri,Pengawas,Pimpinan']],function (){

    Route::get('/dashboard','AdminController@dashboard');
    Route::post('/changePassword','AdminController@changePassword')->name('changePassword');

});

KPV1/blog/resources/views/forms/formmodal.blade.php
@extends('layout.master')
@section('content')
    <script type="text/javascript">

        var save_method; //for save method string
        var table;

        $(document).ready(function () {
            table = $('#example').DataTable({
                "ajax": "<?php echo url('/datamodal') ?>"
            });
        });

        function reload() {
            table.ajax.reload(null, false); //reload datatable ajax
        }

        function reloadpage() {
            location.reload();
        }

        function add() {
            save_method = 'add';
            $('#formmodal')[0].reset(); // reset form on modals
            $('#modal_form').modal('show'); // show bootstrap modal
            $('.modal-title').text('Tambah Modal'); // Set Title to Bootstrap modal title
            $('[name="kode"]').prop("readonly", false);
        }

        function save() {
            var url = "";
            if (save_method === 'add') {
                url = "<?php echo url('/simpanmodal') ?>";
            } else {
                url = "<?php echo url('/updatemodal') ?>";
            }
            $.ajax({
                url: url,
                type: "POST",
                data: $('#formmodal').serialize(),
                dataType: "JSON",
                success: function (data) {
                    if(data.errors){
                        jQuery.each(data.errors, function(key, value){
                            jQuery('.alert-danger').show();
                            jQuery('.alert-danger').append('<p>'+value+'</p>');
                        });
                    }else{
                        alert(data.status);
                        $('#modal_form').modal('hide');
                        reload();
                    }
                },
                error: function (request, status, error) {
                    json = $.parseJSON(request.responseText);
                    $.each(json.errors, function(key, value){
                        $('.alert-danger').show("");
                        $('.alert-danger').append('<p>'+value+'</p>');
                    });
                }
            });
        }

        function ganti(id) {

            save_method = 'update';
            $('#formmodal')[0].reset(); // reset form on modals
            $('#modal_form').modal('show'); // show bootstrap modal when complete loaded
            $('.modal-title').text('Ganti Modal'); // Set title to Bootstrap modal title


            //Ajax Load data from ajax
            $.ajax({
                url: "<?php echo url('/'); ?>" + "/getmodal/" + id,
                type: "GET",
                dataType: "JSON",
                success: function (data) {
                    $('[name="kode"]').prop("readonly", true);

                    $('[name="kode"]').val(data.id_modal);
                    $('[name="modal_awal"]').val(data.jumlah_modal_awal);
                    $('[name="modal_sekarang"]').val(data.jumlah_modal_sekarang);
                }, error: function (jqXHR, textStatus, errorThrown) {
                    alert('Error get data');
                }
            });
        }
    </script>

    <section class="content-header">
        <h1>
            Manage Pegawai
        </h1>
        <ol class="breadcrumb">
            {{--<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>--}}
            {{--<li><a href="#">Tables</a></li>--}}
            {{--<li class="active">Simple</li>--}}
        </ol>
    </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <div class="box">
                        @if(auth()->user()->role=='Pimpinan')
                        <div class="box-header">
                            <button class="btn btn-success" onclick="add();"><i class="glyphicon glyphicon-plus"></i>
                                Tambah Modal
                            </button>
                            <button class="btn btn-default" onclick="reload();"><i
                                    class="glyphicon glyphicon-refresh"></i> Reload
                            </button>
                        </div>
                        @endif
                        <div class="box-body table-responsive no-padding">

                            <table id="example" class="table table-hover" style="text-align-last: center;">
                                <thead>
                                <tr>
                                    <th>Kode</th>
                                    <th>jumlah Modal Awal</th>
                                    <th>jumlah Modal Sekarang</th>
                                    <th>Aksi</th>
                                </tr>
                                </thead>
                                <tbody>
                                </tbody>
                                <tfoot>
                                <tr>
                                    <th>Kode</th>
                                    <th>jumlah Modal Awal</th>
                                    <th>jumlah Modal Sekarang</th>
                                    <th>Aksi</th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </section>


    <div class="modal fade" id="modal_form" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h3 class="modal-title">Form Modal</h3>
                </div>
                <div class="modal-body form">
                    <form action="#" id="formmodal" class="form-horizontal">
                        <div class="alert alert-danger" style="display:none">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                        <input name="_token" type="hidden" id="_token" value="{{ csrf_token() }}"/>
                        <div class="form-body">
                            <div class="form-group">
                                {{--<label type="hidden" class="control-label col-md-3">Kode</label>--}}
                                <div class="col-md-9">
                                    <input name="kode" type="hidden" class="form-control" type="text"
                                           placeholder="Kode">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3">Jumlah Modal Awal</label>
                                <div class="col-md-9">
                                    <input name="modal_awal" class="form-control" type="number" placeholder="Nama">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3">Jumlah Modal Sekarang</label>
                                <div class="col-md-9">
                                    <input name="modal_sekarang" class="form-control" type="number"
                                           placeholder="Alamat">
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" id="btnSave" onclick="save();" class="btn btn-primary">Save</button>
                    <button type="button" onclick="reloadpage();" class="btn btn-danger" data-dismiss="modal">Cancel</button>
                </div>
            </div>
        </div>
    </div>
@stop

KPV1/blog/resources/views/forms/formnasabah.blade.php
@extends('layout.master')

@section('content')
    <script type="text/javascript">
        $(document).ready(function () {
            $('#Date').datepicker({
                format: "dd-mm-yyyy"
            });
        });
    </script>
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Nasabah
            <small>KSP Bangun Jaya Mandiri</small>
        </h1>
        {{--<ol class="breadcrumb">--}}
        {{--<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>--}}
        {{--<li><a href="#">Examples</a></li>--}}
        {{--<li class="active">Blank page</li>--}}
        {{--</ol>--}}
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <button type="button" class="btn btn-success" data-toggle="modal" data-target="#myModal"><i class=" glyphicon glyphicon-plus"></i>Tambah Petugas</button>
                        <button class="btn btn-default" ><i class="glyphicon glyphicon-refresh"></i> Reload</button>
                    </div>
                    <div class="box-body table-responsive no-padding">

                        <table id="example" class="table table-hover" style="text-align-last: center;">

                            <thead>
                            <tr>
                                {{--<th>Kode</th>--}}
                                <th>Nama</th>
                                <th>Telp</th>
                                <th>Alamat KTP</th>
                                <th>Alamat Sekarang</th>
                                {{--<th>Tempat Lahir</th>--}}
                                {{--<th>Tanggal Lahir</th>--}}
                                {{--<th>Jenis Kelamin</th>--}}
                                <th>Status</th>
                                <th>Nama UMKM</th>
                                <th>Foto KTP</th>
                                {{--<th>Foto KK</th>--}}
                                <th>Option</th>
                            </tr>
                            </thead>
                            @foreach($data_nasabah as $nasabah)
                                <tbody>
                                {{--<td>{{$petugas->id}}</td>--}}
                                <td>{{$nasabah->nama}}</td>
                                <td>{{$nasabah->telp}}</td>
                                <td>{{$nasabah->alamat_ktp}}</td>
                                <td>{{$nasabah->alamat_sekarang}}</td>
                                {{--<td>{{$nasabah->tempat_lahir}}</td>--}}
                                {{--<td>{{$nasabah->tgl_lahir}}</td>--}}
                                {{--<td>{{$nasabah->jkel}}</td>--}}
                                <td>{{$nasabah->status}}</td>
                                <td>{{$nasabah->nama_umkm}}</td>
                                <td>@if($nasabah->foto_ktp)
                                        <img src="{{url('images/nasabah/'. $nasabah->foto_ktp)}}" alt="image" style="width:75px; height:75px;" />
                                    @else
                                        <img src="{{url('images/nasabah/default.jpg')}}" alt="image" style="width:75px; height:75px; margin-right: 10px;" />
                                    @endif</td>
                                {{--<td>{{$nasabah->foto_kk}}</td>--}}
                                <td><a href="#" class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-pencil"></i></a>
                                <a href="/nasabah/{{$nasabah->id}}/delete" class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i></a>
                                </td>
                                </tbody>
                            @endforeach
                            <tfoot>
                            <tr>
                                {{--<th>Kode</th>--}}
                                {{--<th>Nama</th>--}}
                                {{--<th>Alamat</th>--}}
                                {{--<th>Nomor Telepon</th>--}}
                                {{--<th>Tempat Lahir</th>--}}
                                {{--<th>Tanggal Lahir</th>--}}
                                {{--<th>jabatan</th>--}}
                                {{--<th>Option</th>--}}

                            </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>

    {{--modal--}}
    <div class="modal fade" id="myModal" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h3 class="modal-title">Form Petugas</h3>
                </div>
                <div class="modal-body form">
                    <form action="{{route('nasabah.store')}}" method="post" id="form" class="form-horizontal" enctype="multipart/form-data">
                        {{csrf_field()}}

                        <div class="alert alert-danger" style="display:none">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                        <input name="_token" type="hidden" id="_token" value="{{ csrf_token() }}" />
                        <div class="form-body">
                            <div class="form-group">
                                {{--<label type="hidden" class="control-label col-md-3">Kode</label>--}}
                                <div class="col-md-9">
                                    <input name="kode"type="hidden" class="form-control" type="text" placeholder="Kode">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3">ID_PETUGAS</label>
                                <div class="col-md-9">
                                    <select class="form-control" name="id_petugas">
                                        @foreach ($dataku as $data)
                                            <option value="{{ $data->id }}">{{$data->id }}[{{ $data->nama}}]
                                            </option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3">Nama</label>
                                <div class="col-md-9">
                                    <input name="nama" class="form-control" type="text" placeholder="Nama">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3">No Telpon</label>
                                <div class="col-md-9">
                                    <input name="telp" class="form-control" type="text" placeholder="No Telpon">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3">Alamat Sesuai KTP</label>
                                <div class="col-md-9">
                                    <input name="alamat_ktp" class="form-control" type="text" placeholder="Alamat">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3">Alamat Sekarang</label>
                                <div class="col-md-9">
                                    <input name="alamat_sekarang" class="form-control" type="text" placeholder="Alamat">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3">Tempat Lahir</label>
                                <div class="col-md-9">
                                    <input name="tempat_lahir" class="form-control" type="text" placeholder="Tempat Lahir">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3">Tgl Lahir</label>
                                <div class="col-md-9">
                                    <input name="tgl_lahir" id="Date" class="form-control" type="text" placeholder="Tgl Lahir">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3">Jenis Kelamin</label>
                                <div class="col-md-9">
                                    <select class="form-control" name="jkel">
                                        <option value="Pria">Pria</option>
                                        <option value="Wanita">Wanita</option>
                                    </select>
                                </div>
                            </div>
{{--                            <div class="form-group">--}}
{{--                                <label class="control-label col-md-3">Jenis Kelamin</label>--}}
{{--                                <div class="col-md-9">--}}
{{--                                    <input name="jkel" class="form-control" type="text" placeholder="jkel">--}}
{{--                                </div>--}}
{{--                            </div>--}}
                            <div class="form-group">
                                <label class="control-label col-md-3">>status</label>
                                <div class="col-md-9">
                                    <select class="form-control" name="status" >
                                        <option value="Menikah">Menikah</option>
                                        <option value="Belum Menikah">Belum Menikah</option>
                                    </select>
                                </div>
                            </div>
{{--                            <div class="form-group">--}}
{{--                                <label class="control-label col-md-3">status</label>--}}
{{--                                <div class="col-md-9">--}}
{{--                                    <input name="status" class="form-control" type="text" placeholder="status">--}}
{{--                                </div>--}}
{{--                            </div>--}}
                            <div class="form-group">
                                <label class="control-label col-md-3">Nama UMKM</label>
                                <div class="col-md-9">
                                    <input name="nama_umkm" class="form-control" type="text" placeholder="Nama UMKM">
                                </div>
                            </div>
                            <div class="form-group">
                                <label  class="control-label col-md-3">Foto KTP</label>
                                <div class="col-md-9">
                                <img id="img-upload" width="420" height="200">
                                <input name="foto_ktp" type="file" class="uploads form-control" id="imgInp">
                                </div>
                            </div>
                            {{--<div class="form-group">--}}
                                {{--<label class="control-label col-md-3">Upload Image</label>--}}
                                {{--<div class="input-group">--}}
                                    {{--<div class="col-md-9">--}}
                                    {{--<span class="input-group-btn">--}}
                                        {{--<span class="btn btn-default btn-file">--}}
                                            {{--Browse… <input type="file" id="imgInp">--}}
                                        {{--</span>--}}
                                    {{--</span>--}}

                                    {{--<input name="foto_ktp" type="text" class="uploads form-control" readonly>--}}

                                    {{--<img id='img-upload'/>--}}
                                    {{--</div>--}}
                                {{--</div>--}}
                            {{--</div>--}}

                            <div class="modal-footer">
                                <button type="submit"  class="btn btn-primary">Save</button>
                                <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
                            </div>

                        </div>

                    </form>
                </div>

            </div>
        </div>
    </div>

@endsection